### ISSUE TITLE
recon/domains-hosts/shodan_hostname

### ISSUE THREAD

**Issue by ramzil000** [lanmaster53/recon-ng#10]
Traceback (most recent call last):
  File "/usr/share/recon-ng/recon/core/module.py", line 289, in do_run
    self.module_run(*params)
  File "/root/.recon-ng/modules/recon/domains-hosts/shodan_hostname.py", line 25, in module_run
    results = self.search_shodan_api(query, limit)
  File "/usr/share/recon-ng/recon/mixins/search.py", line 129, in search_shodan_api
    if resp.json() == None:
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by lanmaster53** [comment]
I can tell by the error alone that you aren't getting valid JSON back from the API. But without knowing what payload you used to recreate the issue, we have no way to figure out what's going on. It seems to be working fine otherwise.

**Comment by lanmaster53** [comment]
Closing due to lack of response.
