### ISSUE TITLE
Issue with reverse_resolve module

### ISSUE THREAD

**Issue by lolcatlolcat** [lanmaster53/recon-ng#127]
Getting an error using the `recon/hosts-hosts/reverse_resolve` module. Here is the module setup:
``` 
Options:
  Name    Current Value                       Required  Description
  ------  -------------                       --------  -----------
  SOURCE  query select ip_address from hosts  yes       source of input (see 'info' for details)
```
I have 543 hosts in the hosts table fwiw. Upon running the module, it gets a way through and then dumps this error message:
```
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dns/reversename.py", line 52, in from_address
    v6 = dns.ipv6.inet_aton(text)
  File "/usr/lib/python3/dist-packages/dns/ipv6.py", line 114, in inet_aton
    text = text.encode()
AttributeError: 'NoneType' object has no attribute 'encode'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/share/recon-ng/recon/core/module.py", line 347, in do_run
    self.run()
  File "/usr/share/recon-ng/recon/core/module.py", line 341, in run
    self.module_run(*params)
  File "/home/user/.recon-ng/modules/recon/hosts-hosts/reverse_resolve.py", line 23, in module_run
    addr = dns.reversename.from_address(address)
  File "/usr/lib/python3/dist-packages/dns/reversename.py", line 61, in from_address
    byte for byte in dns.ipv4.inet_aton(text)]
  File "/usr/lib/python3/dist-packages/dns/ipv4.py", line 46, in inet_aton
    text = text.encode()
AttributeError: 'NoneType' object has no attribute 'encode'
------------------------------------------------------------
```
Any ideas what could be causing the issue? Running the latest version of recon-ng on Kali Linux.

**Comment by lanmaster53** [comment]
Wrong repository. Transferring.
