### ISSUE TITLE
recon/netblocks-companies/whois_orgs module Error message 

### ISSUE THREAD

**Issue by yonaszeru** [lanmaster53/recon-ng#142]
I am using the whois_orgs module. But I am getting the following error message. I don't know what to make of it, If anybody has an idea what's going on. Thanks 

Traceback (most recent call last):                                                                                                                                         
  File "/home/kali/recon-ng/recon/core/module.py", line 347, in do_run                                                                                                     
    self.run()                                                                                                                                                             
  File "/home/kali/recon-ng/recon/core/module.py", line 341, in run                                                                                                        
    self.module_run(*params)                                                                                                                                               
  File "/home/kali/.recon-ng/modules/recon/netblocks-companies/whois_orgs.py", line 25, in module_run                                                                      
    if ref in resp.json()['net']:                                                                                                                                          
  File "/home/kali/.local/lib/python3.9/site-packages/requests/models.py", line 910, in json                                                                               
    return complexjson.loads(self.text, **kwargs)                                                                                                                          
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads                                                                                         
    return _default_decoder.decode(s)                                                                                                                                      
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode                                                                                         
    obj, end = self.raw_decode(s)                                                                                                                                          
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode                                                                                     
    return self.scan_once(s, idx=_w(s, idx).end())                                                                                                                         
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)                                                                                               
------------------------------------------------------------                                                                                                               
[!] Something broken? See https://github.com/lanmaster53/recon-ng/wiki/Troubleshooting#issue-reporting.

**Comment by lanmaster53** [comment]
This is the core framework repository. All module-related issues should be created on the marketplace repository at https://github.com/lanmaster53/recon-ng-marketplace. I will transfer this issue there. Thanks!
