### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by Cy-Beard** [lanmaster53/recon-ng#165]
There are a few modules that have the same error when i attempt to run it.
The current 2 that I am using at the moment are hibp_paste & hibp_breach.
The error is as follows:
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 704, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1043, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 786, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='haveibeenpwned.com', port=443): Max retries exceeded with url: /api/v3/pasteaccount/<domain>.com (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/recon-ng/recon/core/module.py", line 342, in do_run
    self.run()
  File "/usr/share/recon-ng/recon/core/module.py", line 336, in run
    self.module_run(*params)
  File "/root/.recon-ng/modules/recon/contacts-credentials/hibp_paste.py", line 44, in module_run
    resp = self.request('GET', base_url.format(endpoint, quote_plus(account)), headers=headers)
  File "/usr/share/recon-ng/recon/core/framework.py", line 824, in request
    resp = getattr(requests, method.lower())(url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='haveibeenpwned.com', port=443): Max retries exceeded with url: /api/v3/pasteaccount/<domain>.com (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)')))
------------------------------------------------------------
[!] Something broken? See https://github.com/lanmaster53/recon-ng/wiki/Troubleshooting#issue-reporting.

I replaced the actual domain with <domain> for confidentiality reasons. 
Any help on this would be appreciated.

**Comment by lanmaster53** [comment]
All module related issues, including dependencies, should be raised in the [module repository](https://github.com/lanmaster53/recon-ng-marketplace/issues).

Also, all Recon-ng does is make simple web requests. If it is unable to reach the various resources it is trying to reach out to, then you will receive connection errors like this. Therefore, it has to be a local networking issue outside of Recon-ng.
