### ISSUE TITLE
recon-ng][default][html] > run

### ISSUE THREAD

**Issue by Jweim1983** [lanmaster53/recon-ng#173]
Traceback (most recent call last):                                           
  File "/usr/share/recon-ng/recon/core/module.py", line 342, in do_run       
    self.run()                                                               
  File "/usr/share/recon-ng/recon/core/module.py", line 323, in run          
    self._validate_options()                                                 
  File "/usr/share/recon-ng/recon/core/framework.py", line 665, in _validate_options                                                                      
    raise FrameworkException(f"Value required for the '{option}' option.")   
recon.core.framework.FrameworkException: Value required for the 'CUSTOMER' option.

**Comment by AE-001-1001** [comment]
you need to type "options set CUSTOMER customer"
"customer" obviously is whatever name you desire i guess.
