### ISSUE TITLE
I updated my version of linux after which this started to happen, Please Help. :AttributeError:

### ISSUE THREAD

**Issue by khanarslaan7861** [lanmaster53/recon-ng#39]
Traceback (most recent call last):
  File "./recon-ng", line 58, in <module>
    recon_ui(args)
  File "./recon-ng", line 43, in recon_ui
    x.start(*options)
  File "/root/recon-ng/recon/core/base.py", line 76, in start
    self._init_workspace(workspace)
  File "/root/recon-ng/recon/core/base.py", line 202, in _init_workspace
    self._migrate_db()
  File "/root/recon-ng/recon/core/base.py", line 258, in _migrate_db
    tmp = self.get_random_str(20)
  File "/root/recon-ng/recon/core/framework.py", line 229, in get_random_str
    return ''.join(random.choice(string.lowercase) for i in range(length))
  File "/root/recon-ng/recon/core/framework.py", line 229, in <genexpr>
    return ''.join(random.choice(string.lowercase) for i in range(length))
AttributeError: module 'string' has no attribute 'lowercase'

**Comment by lanmaster53** [comment]
I just pushed a fix to staging if you want to checkout that branch to migrate your workspace. You can switch back afterward.
