### ISSUE TITLE
sqlite3.OperationalError: no such table: pushpin

### ISSUE THREAD

**Issue by endbehavi0r** [lanmaster53/recon-ng#66]
```
Traceback (most recent call last):
  File "./recon-ng", line 57, in <module>
    recon_ui(args)
  File "./recon-ng", line 42, in recon_ui
    x.start(*options)
  File "/usr/share/recon-ng/recon/core/base.py", line 73, in start
    self._init_workspace(workspace)
  File "/usr/share/recon-ng/recon/core/base.py", line 194, in _init_workspace
    self._migrate_db()
  File "/usr/share/recon-ng/recon/core/base.py", line 263, in _migrate_db
    self.query('ALTER TABLE pushpin RENAME TO pushpins')
  File "/usr/share/recon-ng/recon/core/framework.py", line 342, in query
    return self._query(path, *args, **kwargs)
  File "/usr/share/recon-ng/recon/core/framework.py", line 354, in _query
    cur.execute(query)
sqlite3.OperationalError: no such table: pushpin
```
Error saying that table pushpin does not exist.

**Comment by lanmaster53** [comment]
https://github.com/lanmaster53/recon-ng/blob/master/recon/core/base.py#L272 in the latest version is a migration that renames this table. Your error is occurring during this migration and showing that line to be line 263. Therefore, you are definitely using an older version of the framework. Also, that migration is from many years ago. There is likely no good reason for your database to be doing that. Have you manually messed with your database? My recommendation would be to manually remove the default workspace at ~/.recon-ng/workspaces/default and load the framework again.

**Comment by endbehavi0r** [comment]
Thanks. Removing ~/.recon-ng/workspaces/default helped.
