### ISSUE TITLE
Python upgraded to 3.6.8 new set of errors (Raspberry Pi 3B+)

### ISSUE THREAD

**Issue by AnonPK3** [lanmaster53/recon-ng#79]
pi@raspberrypi:/etc/python3.6.8 $ python3  --version
Python 3.6.8

pi@raspberrypi:/GitArchive/recon-ng $ ls
docker-compose.yml  Dockerfile  LICENSE  README.md  recon  recon-cli  recon-ng  recon-web  REQUIREMENTS  VERSION

pi@raspberrypi:/GitArchive/recon-ng $ ./recon-ng
Traceback (most recent call last):
  File "./recon-ng", line 8, in <module>
    from recon.core import base
  File "/GitArchive/recon-ng/recon/core/base.py", line 14, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

pi@raspberrypi:/GitArchive/recon-ng $ sudo ./recon-ng
Traceback (most recent call last):
  File "./recon-ng", line 8, in <module>
    from recon.core import base
  File "/GitArchive/recon-ng/recon/core/base.py", line 14, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

pi@raspberrypi:/GitArchive/recon-ng $ python3 recon-ng
Traceback (most recent call last):
  File "recon-ng", line 8, in <module>
    from recon.core import base
  File "/GitArchive/recon-ng/recon/core/base.py", line 14, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Comment by AnonPK3** [comment]
Greetings. I do run into oddities with the Pi's now and then vs Linux and the ARM architecture. I tried to get Kali running on a USB stick, booting on my Win 10 machine, but ran into a problem with the latest version. So I still haven't been able to run recon-ng yet. I've only seen HackerSploit run it on YouTube. My skills are not so good, so I would need help to push it further. If you need specific failures from the Pi I am willing to try. Other than videos on YouTube I've never used Docker. Thanks for getting back.

**Comment by lanmaster53** [comment]
If you follow a tutorial on installing Docker (not even sure it is possible on Raspberry Pi), then the Recon-ng wiki will help you get Recon-ng setup with a working Docker install. Also, do some Google searching on the installing lxml on Raspberry Pi. There are known complications and possible workarounds.

**Comment by 0x646e78** [comment]
@AnonPK3 I believe that will be due to missing libraries on your system:

`sudo apt-get install -y i  libxml2-dev libxslt1-dev`

libxml install page: https://lxml.de/installation.html#installation

Having said this I'd suggest also using the Docker image, or at least a venv. python-lxml from apt can also provide the dependency.

**Comment by AnonPK3** [comment]
Greetings,

   I have tried these suggestions and still cannot run the program. Here is what I ran into :

#1. the i designation messes up the command. I did not see an i option on the man page for apt-get.
#2. sudo apt-get install -y libxml2-dev libxslt1-dev  (command worked)
#3. Could not locate venv.python-lxml , instead ran another command.
#4. sudo apt-get install python-lxml  (command worked)
#5. Still unable to run recon-ng from its own subdirectory.
#6. Error given : Traceback (most recent call last):
                              File "recon-ng", line 8, in <module>
                              from recon.core import base
                              File "/GitArchive/recon-ng/recon/core/base.py", line 14, in <module>
                              import yam1
                              ModuleNotFoundError: No module named 'yam1'

Within this sub-directory are the files : docker-compose.yml  DockerFile  LICENSE  README.md   recon  recon-cli  recon-ng  recon-web  REQUIREMENTS  VERSION

Thanks for the try.
Preston Knodell III


________________________________

**Comment by 0x646e78** [comment]
@AnonPK3 have you edited the file `recon/core/base.py` ? The error reports `yam1` but the module is `yaml` - note the 1 and l. In your original issue report this was correctly `yaml`. You man want to start from a clean checkout of the repo.

**Comment by lanmaster53** [comment]
@0x646e78 Are you on the Recon-ng Slack? If not, please join and hit me up. I wanted to chat with you. Sign up here https://github.com/lanmaster53/recon-ng/wiki/Getting-Started#help. Thanks!
